blank_issues_enabled: false
contact_links:
  - name: 讨论交流 / Communication
    url: https://github.com/micheal-death/clash-verge-rev/issues
    about: 在本仓库 issues 中反馈或讨论 / Discuss in this repository's issues
